### ISSUE TITLE
Small issue in README examples

### ISSUE THREAD

**Issue by woodpig07** [derhuerst/gulp-scale-images#6]
First of all, I really like your work for this plugin as I do prefer `sharp` over `gm`.

It looks there were two minor mistakes in your README examples that prevent the code from working as expected:
https://github.com/derhuerst/gulp-scale-images#definining-scale-instructions-based-on-metadata
```
const computeScaleInstructions = (file, _, cb) => {
	readMetadata(file.path, (err, meta) => {
		if (err) return cb(err)
		file.scale = {
			maxWidth: Math.floor(meta.width / 2),
			maxHeight: Math.floor(meta.height / 2)
		}
		cb(null, scale)
	})
}
```
The `cb(null, scale)` should be `cb(null, file)`

https://github.com/derhuerst/gulp-scale-images#custom-output-file-names
```
const computeFileName = (output, scale, cb) => {
	const fileName = [
		path.basename(output.path, output.extname), // strip extension
		scale.maxWidth + 'w',
		scale.format || output.extname
	].join('.')
}
```
It's missing `cb(null, fileName)` at the last line before the closing bracket.

**Comment by derhuerst** [comment]
Good catch!
